name: ci-test

on:
  push:
    branches: [develop, master, ch-cicd-psql-deploy-177432339]
  pull_request:
    branches: [develop, master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: customer_service_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate
      - name: set database url env variable
        run: echo "DBURL =>> ${DATABASE_URL}"
        env:
          DATABASE_URL: "postgresql://root:secret@localhost:5432/customer_service_test?sslmode=disable"
      - name: Run migrations
        run: migrate -path ./databases/migrations/ -database "postgresql://root:secret@localhost:5432/customer_service_test?sslmode=disable" -verbose up

      - name: Test
        run: make test
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g codeclimate-test-reporter
      - run: make testcover
      - run: |
          echo "CODECLIMATE_REPO_TOKEN=521b528b1f9ee802f966d62a3cb5cf7a5bfbb3366b0cadfd2b6aaa1052bbd021"
        env:
          CC_TEST_REPORTER_ID: 521b528b1f9ee802f966d62a3cb5cf7a5bfbb3366b0cadfd2b6aaa1052bbd021
          CODECLIMATE_API_HOST : https://codebeat.co/webhooks/code_coverage \
          CODECLIMATE_REPO_TOKEN : 521b528b1f9ee802f966d62a3cb5cf7a5bfbb3366b0cadfd2b6aaa1052bbd021
      - run: codeclimate-test-reporter < cover.out
  